[build-system]
requires = ["setuptools>=64", "setuptools_scm[toml]>=7"]
build-backend = "setuptools.build_meta"


[project]
name = "smt"
description = ""
requires-python = ">=3.10"
version = "0.0.0"
dependencies = [
	"jax==0.4.28",
	"jaxlib==0.4.28",
	"numpy==1.26.4",
	"tqdm==4.66.4",
]
